### ISSUE TITLE
Players push themself (dont stop running)

### ISSUE THREAD

**Issue by diamond-dev1** [Daily-Datapackers/datapack#70]
Players push themself 

**How to fix**
- With plugins

**Assignees**
- @DiamondDP

**Comment by HoodieRocks** [comment]
without nitty gritty server code manipulation, spigot's api is not capable of stopping collisions without teams

**Comment by HoodieRocks** [comment]
i wont be able to, but other plugins can, backtotheroots (a plugin for emulating 1.8 features) might be able to (although it wont be toggleable), the best option seems to be just disabling collisions globally on every team individually
